# Generated by Django 5.0.6 on 2026-06-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritageresource',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
