# Generated by Django 5.0.6 on 2026-06-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_consensus_state_and_vote_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='consensus_auto_resolved',
            field=models.BooleanField(default=False, help_text='True if `status=RESOLVED` was set by the consensus engine rather than by a human clicking « marquer comme résolu ».'),
        ),
    ]
